Repository cse110-sp23-group21/map-my-future, pull requests merged in 2023-06, with the labels that each got.

#47 FortuneEngine modifications
  src/engine-html-test.html
  src/engine.js
Labels: enhancement

#68 Add Yin Yang Coin mini-app to the `dev` branch
  assets/coin/background.png
  assets/coin/bgm-background.mp3
  assets/coin/bgm-coin-flip.ogg
  assets/coin/chinese.stxingka.ttf
  assets/coin/instruction-coin.png
  assets/coin/instruction-line.png
  assets/coin/line-broken.png
  assets/coin/line-solid.png
  src/mini-apps/yin_yang_coin/yin-yang32x32.png
  src/mini-apps/yin_yang_coin/yin_yang_coin.html
  src/mini-apps/yin_yang_coin/yin_yang_coin.js
  src/mini-apps/yin_yang_coin/yin_yang_coin.json
  src/mini-apps/yin_yang_coin/yin_yang_coin_styles.css
Labels: enhancement, Yin Yang Coin

#63 New music and favicon
  assets/Waltz-of-the-fortune-teller.mp3
  assets/fortune-teller_32x32.png
  src/app.js
  src/index.html
Labels: enhancement, front end

#60 Updated minifier step (new minimize.sh script)
  .github/minimize.sh
  .github/workflows/cicd_push_to_main.yml
Labels: enhancement, CI/CD

#89 Disabled "tagname-lowercase" HTML linting rule
  .htmlhintrc
Labels: bug, Molydomancy, CI/CD

#94 Molybdomancy fix with a minor change of info home page
  src/index.html
  src/mini-apps/molybdomancy/molybdomancy-styles.css
  src/mini-apps/molybdomancy/molybdomancy.html
Labels: bug, enhancement, Molydomancy

#96 Add documentation to Yin Yang Coin
  src/mini-apps/cartomancy/cartomancy.html
  src/mini-apps/cartomancy/tarot-card32x32.png
  src/mini-apps/fortune_stick/fortune_stick.html
  src/mini-apps/fortune_stick/fortune_stick32x32.png
  src/mini-apps/yin_yang_coin/yin_yang_coin.html
  src/mini-apps/yin_yang_coin/yin_yang_coin.js
  src/mini-apps/yin_yang_coin/yin_yang_coin.json
  src/mini-apps/yin_yang_coin/yin_yang_coin_styles.css
Labels: documentation, Yin Yang Coin

#97 Refine main page design.
  .github/workflows/cicd_push_to_main.yml
  .stylelintrc.json
  assets/background.jpg
  assets/badhead.ttf
  assets/bgm-side.wav
  assets/side-cart.png
  assets/side-coin.png
  assets/side-moly.png
  assets/side-stick.png
  docs/FortuneEngine.html
  docs/engine.js.html
  docs/global.html
  docs/index.html
  src/app.js
  src/index.html
  src/styles.css
Labels: enhancement, help wanted, front end

#107 Polish for Molybdomancy
  src/assets/moly/action-button-hover.wav
  src/assets/moly/action-button-hover2.mp3
  src/assets/moly/action-button-press1.wav
  src/assets/moly/action-button-press2.wav
  src/mini-apps/molybdomancy/molybdomancy.js
Labels: Molydomancy, polish

#106 Polish for Yin Yang Coin
  src/assets/coin/action-button-press1.wav
  src/assets/coin/action-button-press2.mp3
  src/assets/coin/action-button-press3.mp3
  src/assets/coin/action-button-press4.wav
  src/assets/coin/hex-reveal.mp3
  src/assets/coin/line-reveal1.mp3
  src/assets/coin/line-reveal2.mp3
  src/mini-apps/yin_yang_coin/yin_yang_coin.js
Labels: Yin Yang Coin, polish

#101 Fix Linting for Molybdomancy
  .stylelintrc.json
  src/mini-apps/molybdomancy/molybdomancy-styles.css
  src/mini-apps/molybdomancy/molybdomancy.html
  src/mini-apps/molybdomancy/molybdomancy.js
Labels: Molydomancy, CI/CD

#105 Fix for Background Music Autoplay Issues
  src/app.js
  src/autoplay.js
  src/index.html
  src/mini-apps/cartomancy/cartomancy.js
  src/mini-apps/fortune_stick/fortune_stick.js
  src/mini-apps/molybdomancy/molybdomancy.js
  src/mini-apps/yin_yang_coin/yin_yang_coin.js
Labels: bug, cleanup

#110 Added Playwright Testing Framework
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.js
  tests-examples/demo-todo-app.spec.js
  tests/e2e/example.spec.js
  tests/e2e/main_page/main_page.spec.js
  tests/e2e/molybdomancy/molybdomancy.spec.js
  tests/unit/engine.test.js
Labels: testing, CI/CD

#112 Fixed Linting (Currently Passing all Linters)
  .gitignore
  .vscode/settings.json
  src/app.js
  src/autoplay.js
  src/mini-apps/cartomancy/cartomancy.html
  src/mini-apps/cartomancy/cartomancy.js
  src/mini-apps/fortune_stick/fortune_stick.js
  src/mini-apps/molybdomancy/molybdomancy.js
  src/mini-apps/yin_yang_coin/yin_yang_coin.js
  src/mini-apps/yin_yang_coin/yin_yang_coin_styles.css
Labels: CI/CD, cleanup

#114 Test main page
  tests/e2e/main_page/main_page.spec.js
Labels: testing

#117 Test Molybdomancy Mini-App
  tests/e2e/molybdomancy/molybdomancy.spec.js
Labels: mini-apps, Molydomancy, testing

#126 Added Documentation to the Molybdomancy Mini-App
  src/mini-apps/molybdomancy/molybdomancy-styles.css
  src/mini-apps/molybdomancy/molybdomancy.html
  src/mini-apps/molybdomancy/molybdomancy.js
Labels: documentation, Molydomancy

#127 Added Documentation
  src/app.js
  src/autoplay.js
  src/engine.js
  src/mini-apps/cartomancy/cartomancy.js
  src/mini-apps/fortune_stick/fortune_stick.css
  src/mini-apps/fortune_stick/fortune_stick.js
  src/mini-apps/molybdomancy/molybdomancy.js
  src/mini-apps/yin_yang_coin/yin_yang_coin.js
Labels: documentation, Molydomancy, Fortune Sticks, Cartomancy

#128 Updated Engine.js JSDocs
  src/engine.js
Labels: documentation, back end
