Repository cse110-sp23-group21/map-my-future, pull requests merged in 2023-05, with the labels that each got.

#10 Update and rename linter.yml to cicd.yml
  .github/workflows/cicd.yml
  .github/workflows/linter.yml
Labels: documentation, enhancement

#9 Created Repository Skeleton
  index.html
  src/engine.js
  src/mini-apps/cartomancy.js
  src/mini-apps/fortune_stick.js
  src/mini-apps/molybdomancy.js
  src/mini-apps/yin_yang_coin.js
Labels: front end, back end

#12 Sprint1 Main Page Map Design
  .DS_Store
  app.js
  assets/audio_off.png
  assets/audio_on.png
  assets/info.png
  assets/map-my-future-bgm.ogg
  docs/FortuneEngine.html
  docs/cartomancy.js.html
  docs/engine.js.html
  docs/global.html
  docs/index.html
  docs/molybdomancy.js.html
  index.html
  styles.css
Labels: enhancement, front end

#29 Moved source code files into src directory
  app.js
  src/app.js
  src/engine-html-test.html
  src/index.html
  src/styles.css
Labels: enhancement

#15 Cleanup + improvements for CI/CD (second attempt)
  .github/workflows/cicd.yml
  .github/workflows/cicd_pull_requests.yml
  .github/workflows/cicd_push_to_dev.yml
  .github/workflows/cicd_push_to_main.yml
Labels: enhancement

#37 Update dev with CI/CD changes
  .DS_Store
  .github/workflows/cicd.yml
  .github/workflows/cicd_pull_requests.yml
  .github/workflows/cicd_push_to_dev.yml
  .github/workflows/cicd_push_to_main.yml
  .gitignore
  config.json
  dist/app.js
  dist/cartomancy.js
  dist/engine-html-test.html
  dist/engine.js
  dist/fortune_stick.js
  dist/index.html
  dist/molybdomancy.js
  dist/styles.css
  dist/yin_yang_coin.js
  docs/FortuneEngine.html
  docs/data/search.json
  docs/engine.js.html
  docs/fonts/Inconsolata-Regular.ttf
  docs/fonts/OpenSans-Regular.ttf
  docs/fonts/WorkSans-Bold.ttf
  docs/index.html
  docs/scripts/core.js
  docs/scripts/core.min.js
  docs/scripts/resize.js
  docs/scripts/search.js
  docs/scripts/search.min.js
  docs/scripts/third-party/Apache-License-2.0.txt
  docs/scripts/third-party/fuse.js
  docs/scripts/third-party/hljs-line-num-original.js
  docs/scripts/third-party/hljs-line-num.js
  docs/scripts/third-party/hljs-original.js
  docs/scripts/third-party/hljs.js
  docs/scripts/third-party/popper.js
  docs/scripts/third-party/tippy.js
  docs/scripts/third-party/tocbot.js
  docs/scripts/third-party/tocbot.min.js
  docs/styles/clean-jsdoc-theme-base.css
  docs/styles/clean-jsdoc-theme-dark.css
  docs/styles/clean-jsdoc-theme-light.css
  docs/styles/clean-jsdoc-theme.min.css
  package-lock.json
  package.json
  src/app.js
  src/engine.js
  src/index.html
  src/mini-apps/fortune_stick/fortune_stick.js
  src/mini-apps/molybdomancy/molybdomancy.js
  src/mini-apps/yin_yang_coin/yin_yang_coin.js
  src/styles.css
  tests/sample.test.js
Labels: enhancement

#44 Fixed Semi-Standard Linter Bug
  .github/workflows/cicd_pull_requests.yml
  .github/workflows/cicd_push_to_dev.yml
  .github/workflows/cicd_push_to_main.yml
  package.json
Labels: bug, CI/CD

#42 Added `engine.js` documentation
  src/engine.js
Labels: documentation, back end
